development:
  adapter: postgresql
  encoding: unicode
  database: xcelerator
  username: postgres
  password: postgres
  host: localhost
  port: 5432

staging:
  adapter: postgresql
  encoding: unicode
  database: xcelerator
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: test_event
  username: test
  password: test
  host: 172.17.0.1
  port: 32768

